version: '3'
services:
  rsk_node:
    build: .
    restart: on-failure
    hostname: rsk_node
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8545,30303:8545,30303"
      - "8545,30303:8545,30303/udp"
    networks:
      - rsk_network0        

networks:
  rsk_network0:
    external: true

