version: '3'
services:
  rsk-node:
    build: .
    restart: on-failure
    hostname: rsk-node
    extra_hosts: 
      - "rsk-stats:172.19.0.2"
    entrypoint: /root/start.sh
    command: '/usr/bin/supervisord'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
