version: '3'
services:
  rsk-node:
    build: rsk-node
    restart: on-failure
    hostname: rsk-node
    links:
      - rsk-stats
    entrypoint: /root/start.sh
    command: '/usr/bin/supervisord'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"  
  rsk-stats:
    build: rsk-stats
    restart: on-failure
    environment:
      - WS_SECRET=oracle
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
