version: '3.7'
services:
  wdl:
    container_name: wdl
    image: mysql:8.0
    restart: always
    volumes:
      - ./wdl/data:/var/lib/mysql
      - ./wdl/conf.d:/etc/mysql/conf.d/
      - ./wdl/log:/var/log/mysql
      - ./wdl/backup:/backup
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: wdl
      MYSQL_USER: wdl
      MYSQL_PASSWORD: "oracle"
      MYSQL_ROOT_PASSWORD: "oracle"
