version: '2'
services:
  rsk-trx-db:
    container_name: fit-db
    image: mariadb 
    restart: always
    volumes:
      - ${HOME}/fit-db/datadir:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "fit"
      MYSQL_USER: "fit"
      MYSQL_PASSWORD: "oracle"
      MYSQL_ROOT_PASSWORD: "oracle"

