version: '2.1'
services:
  rsk-trx-db:
    container_name: rsk-trx-db
    image: mysql
    restart: always
    volumes:
      - ${HOME}/rsk-trx-db/datadir:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "rsk"
      MYSQL_USER: "rsk"
      MYSQL_PASSWORD: "oracle"
      MYSQL_ROOT_PASSWORD: "oracle"

